apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy01
  labels:
    app: autodeploy01
  namespace: namespace-workflow-1696009028081
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy01
  template:
    metadata:
      labels:
        app: autodeploy01
    spec:
      containers:
        - name: autodeploy01
          image: acrworkflow1696009028081.azurecr.io/image-workflow-1696009028081:latest
          ports:
            - containerPort: 5000