apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy02
  labels:
    app: autodeploy02
  namespace: namespace-workflow-1696009842843
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy02
  template:
    metadata:
      labels:
        app: autodeploy02
    spec:
      containers:
        - name: autodeploy02
          image: acrworkflow1696009842843.azurecr.io/image-workflow-1696009842843:latest
          ports:
            - containerPort: 5000