apiVersion: v1
kind: Service
metadata:
  name: autodeploy04
  namespace: namespace-workflow-1696011078386
spec:
  type: LoadBalancer
  selector:
    app: autodeploy04
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000