apiVersion: v1
kind: Service
metadata:
  name: autodeploy02
  namespace: namespace-workflow-1696009842843
spec:
  type: LoadBalancer
  selector:
    app: autodeploy02
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000