apiVersion: v1
kind: Service
metadata:
  name: autodeploy03
  namespace: namespace-workflow-1696010624563
spec:
  type: LoadBalancer
  selector:
    app: autodeploy03
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000